name: Release

on:
	release:
		types: [published]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DALAMUD_HOME: /tmp/dalamud
        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-dotnet@v6
                with:
                    dotnet-version: 10.0.x

            - name: Download Dalamud
                run: |
                    wget -O /tmp/dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
                    unzip /tmp/dalamud.zip -d $DALAMUD_HOME

            - name: Build Plugin
                run: |
                    dotnet build -c Release -p:EnableWindowsTargeting=true

            - name: Create Package
                run: |
                    ls -la
