<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>2.0.1.0</Version>
    <!-- Manifest fields (see https://github.com/goatcorp/DalamudPackager/blob/827d88dc/DalamudPackager/DalamudPackager.cs#L420) -->
    <Author>katabame</Author>
    <Name>HuntTally</Name>
    <Punchline>モブの討伐数を記録するプラグイン</Punchline>
    <Description>倒したモブの名前と討伐数を記録します</Description>
    <RepoUrl>https://github.com/katabame/HuntTally</RepoUrl>
    <Tags>track;plugin;mob</Tags>
  </PropertyGroup>
</Project>
